// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9pS7KsmTp0WztDyUqBdoHXktDDrDwqHY',
    appId: '1:249550849156:web:516bf474946f9e36cb2ed1',
    messagingSenderId: '249550849156',
    projectId: 'facebook-clone-2c757',
    authDomain: 'facebook-clone-2c757.firebaseapp.com',
    storageBucket: 'facebook-clone-2c757.firebasestorage.app',
    measurementId: 'G-7L9Q9S04HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOuZd9ragjx568SPOvW7R9NqTnnBvokEE',
    appId: '1:249550849156:android:ff8b2a483e72a4c1cb2ed1',
    messagingSenderId: '249550849156',
    projectId: 'facebook-clone-2c757',
    storageBucket: 'facebook-clone-2c757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcG8Unf8vDSnBYHWp3h73SuetFZdEphn0',
    appId: '1:249550849156:ios:8f2391348c45ed1acb2ed1',
    messagingSenderId: '249550849156',
    projectId: 'facebook-clone-2c757',
    storageBucket: 'facebook-clone-2c757.firebasestorage.app',
    iosBundleId: 'com.example.facebookClone',
  );
}
